#!/bin/bash
cd

if [ ! -d "src" ]; then
mkdir src
cd src
virtualenv venv
source venv/bin/activate
git clone https://github.com/jerdna-regeiz/tomaHAWkss.git
cd
else
cd src/tomaHAWkss
git pull
cd
fi

chmod +x src/tomaHAWkss/server/ctfServer/assets/initLib.sh
chmod +x src/tomaHAWkss/server/ctfServer/assets/deploy.sh
cd  src/tomaHAWkss/server/ctfServer/assets/
./initLib.sh
./deploy.sh
cd

pip install -r src/tomaHAWkss/server/ctfServer/idIoT/requirements.txt
cp src/tomaHAWkss/server/ctfServer/scripts/minion minion

salt "*" cmd.run "rm minion"
salt-cp "*" minion  ~/minion
salt "*" cmd.run "chmod +x minion"
salt "*" cmd.run "~/./minion"

source src/venv/bin/activate
cd src/tomaHAWkss/server/ctfServer

python ./main.py
